//Mens Chappal Get Data
export const MENS_GET_REQUEST  =  "MENS_GET_REQUEST"
export const MENS_GET_SUCCESS  =  "MENS_GET_SUCCESS"
export const MENS_GET_FAILUE  =  "MENS_GET_FAILUE"


//Mens Sandal Get Data
export const MENS_SANDAL_GET_REQUEST  =  "MENS_SANDAL_GET_REQUEST"
export const MENS_SANDAL_GET_SUCCESS  =  "MENS_SANDAL_GET_SUCCESS"
export const MENS_SANDAL_GET_FAILUE  =  "MENS_SANDAL_GET_FAILUE"

//Mens Shoes Get Data
export const MENS_SHOES_GET_REQUEST  =  "MENS_SHOES_GET_REQUEST"
export const MENS_SHOES_GET_SUCCESS  =  "MENS_SHOES_GET_SUCCESS"
export const MENS_SHOES_GET_FAILUE  =  "MENS_SHOES_GET_FAILUE"