//Womens Chappal Get Data
export const   WOMENS_CHAPPAL_GET_REQUEST  =  "WOMENS_CHAPPAL_GET_REQUEST"
export const   WOMENS_CHAPPAL_GET_SUCCESS  =  "WOMENS_CHAPPAL_GET_SUCCESS"
export const   WOMENS_CHAPPAL_GET_FAILUE  =  " WOMENS_CHAPPAL_GET_FAILUE"


//Womens Sandal Get Data
export const WOMENS_SANDAL_GET_REQUEST  =  "WOMENS_SANDAL_GET_REQUEST"
export const WOMENS_SANDAL_GET_SUCCESS  =  "WOMENS_SANDAL_GET_SUCCESS"
export const WOMENS_SANDAL_GET_FAILUE  =  "WOMENS_SANDAL_GET_FAILUE"


//Womens Shoes Get Data
export const WOMENS_SHOES_GET_REQUEST  =  "WOMENS_SHOES_GET_REQUEST"
export const WOMENS_SHOES_GET_SUCCESS  =  "WOMENS_SHOES_GET_SUCCESS"
export const WOMENS_SHOES_GET_FAILUE  =  "WOMENS_SHOES_GET_FAILUE"