//Girls Chappal Get Data
export const GIRLS_CHAPPAL_GET_REQUEST  =  "GIRLS_CHAPPAL_GET_REQUEST"
export const GIRLS_CHAPPAL_GET_SUCCESS  =  "GIRLS_CHAPPAL_GET_SUCCESS"
export const GIRLS_CHAPPAL_GET_FAILURE  =  "GIRLS_CHAPPAL_GET_FAILURE"

//Girls Sandal Get Data
export const GIRLS_SANDAL_GET_REQUEST  =  "GIRLS_SANDAL_GET_REQUEST"
export const GIRLS_SANDAL_GET_SUCCESS  =  "GIRLS_SANDAL_GET_SUCCESS"
export const GIRLS_SANDAL_GET_FAILURE  =  "GIRLS_SANDAL_GET_FAILURE"

//Girls Shoes Get Data
export const GIRLS_SHOES_GET_REQUEST  =  "GIRLS_SHOES_GET_REQUEST"
export const GIRLS_SHOES_GET_SUCCESS  =  "GIRLS_SHOES_GET_SUCCESS"
export const GIRLS_SHOES_GET_FAILURE  =  "GIRLS_SHOES_GET_FAILURE"