//Boys Chappal Get Data
export const BOYS_GET_REQUEST  =  "BOYS_GET_REQUEST"
export const BOYS_GET_SUCCESS  =  "BOYS_GET_SUCCESS"
export const BOYS_GET_FAILURE  =  "BOYS_GET_FAILURE"

//Boys Sandal Get Data
export const BOYS_SANDAL_GET_REQUEST  =  "BOYS_SANDAL_GET_REQUEST"
export const BOYS_SANDAL_GET_SUCCESS  =  "BOYS_SANDAL_GET_SUCCESS"
export const BOYS_SANDAL_GET_FAILURE  =  "BOYS_SANDAL_GET_FAILURE"

//Boys Shoes Get Data
export const BOYS_SHOES_GET_REQUEST  =  "BOYS_SHOES_GET_REQUEST"
export const BOYS_SHOES_GET_SUCCESS  =  "BOYS_SHOES_GET_SUCCESS"
export const BOYS_SHOES_GET_FAILURE  =  "BOYS_SHOES_GET_FAILURE"